# CI PIPELINE - Test both from /src and /server
name: CI Pipeline

# Whenever we PR w/ main or merge it (push to main).
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
        # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

        # Generate unique build ID
      - name: Generate build version
        shell: bash
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          BUILD_VERSION="IB-build-${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}-${SHORT_SHA}"
          echo "BUILD_VERSION=$BUILD_VERSION" >> "$GITHUB_ENV"
          echo "Build version: $BUILD_VERSION"
          echo "### Build version: \`$BUILD_VERSION\`" >> "$GITHUB_STEP_SUMMARY"

        # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: |
            package-lock.json
            server/package-lock.json

        # Match CI environment
      - name: Use npm 11
        run: npm install -g npm@11.11.0

      # Frontend
      - name: Install frontend dependencies
        run: npm ci

      - name: Run login tests
        run: npm test -- --watchAll=false --runTestsByPath src/services/authService.js
      
      - name: Run interview Setup tests
        run: npm test -- --watchAll=false --runTestsByPath src/pages/InterviewSetupPage.test.js
      
      - name: Run frontend tests
        run: npm test -- --watchAll=false

      - name: Build React application
        run: npm run build

      # Backend
      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Run server tests
        working-directory: ./server
        run: npm test -- --watchAll=false

   